datadog:
  clusterName: alexf-aks
  env:
    - name: DD_KUBELET_CLIENT_CA
      value: "/host/etc/kubernetes/certs/kubeletserver.crt"
agents:
  volumeMounts:
    - mountPath: /host/etc/kubernetes/certs
      name: kubernetes-certs
  volumes:
    - name: kubernetes-certs
      hostPath:
        path: /etc/kubernetes/certs
        type: DirectoryOrCreate
clusterAgent:
  confd:
    kube_controller_manager.yaml: |-
      cluster_check: true
      init_config:
      instances:
        - prometheus_url: https://kubernetes.default/metrics
          ssl_ca_cert: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
          bearer_token_auth: true
    kube_scheduler.yaml: |-
      cluster_check: true
      init_config:
      instances:
        - prometheus_url: https://kubernetes.default/metrics
          ssl_ca_cert: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
          bearer_token_auth: true
    kube_apiserver_metrics.yaml: |-
      cluster_check: true
      init_config:
      instances:
        - prometheus_url: https://kubernetes.default/metrics
          ssl_ca_cert: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
          bearer_token_auth: true
