controller:
  name: nginx-ingress
  kind: DaemonSet
  service:
    loadBalancerIP: "20.72.177.220"
  metrics:
    enabled: true
    service:
      annotations:
        ad.datadoghq.com/service.check_names: '["nginx_ingress_controller"]'
        ad.datadoghq.com/service.init_configs: '[{}]'
        ad.datadoghq.com/service.instances: >-
          [
            {
              "prometheus_url": "http://%%host%%:9913/metrics"
            }
          ]
  podAnnotations:
    ad.datadoghq.com/controller.check_names: '["nginx"]'
    ad.datadoghq.com/controller.init_configs: '[{}]'
    ad.datadoghq.com/controller.instances: >-
      [
        {
          "nginx_status_url": "http://%%host%%/nginx_status/"
        }
      ]
  config:
    enable-opentracing: "true"
    datadog-collector-host: $DD_AGENT_HOST
    nginx-status-ipv4-whitelist: "10.0.0.0/8"
