controller:
  name: nginx-ingress
  kind: DaemonSet
  service:
    type: NodePort
    nodePorts:
      http: 30080
      https: 30443
    # loadBalancerIP: "20.72.177.220"
  metrics:
    enabled: true
    service:
      annotations:
        ad.datadoghq.com/service.check_names: '["nginx_ingress_controller"]'
        ad.datadoghq.com/service.init_configs: '[{}]'
        ad.datadoghq.com/service.instances: >-
          [
            {
              "prometheus_url": "http://%%host%%:9913/metrics"
            }
          ]
  labels:
    tags.datadoghq.com/env: lab
  podAnnotations:
    ad.datadoghq.com/controller.check_names: '["nginx"]'
    ad.datadoghq.com/controller.init_configs: '[{}]'
    ad.datadoghq.com/controller.instances: >-
      [
        {
          "nginx_status_url": "http://%%host%%/nginx_status/"
        }
      ]
  # https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/configmap/
  config:
    enable-opentracing: "true"
    datadog-collector-host: $DD_AGENT_HOST
    datadog-environment: $DD_ENV
    # Should match pod network
    nginx-status-ipv4-whitelist: "192.168.0.0/16"
    # nginx-status-ipv4-whitelist: "10.0.0.0/8"
