datadog:
  apiKeyExistingSecret: datadog-keys
  criSocketPath: /var/run/crio/crio.sock
  apm:
    enabled: true
  logs:
    enabled: true
    containerCollectAll: true
  processAgent:
    enabled: true
    processCollection: true
  systemProbe:
    enabled: true
  clusterChecks:
    enabled: true
  kubeStateMetricsEnabled: true
  dogstatsd:
    nonLocalTraffic: true
    useHostPort: true
  env:
    - name: DD_ENV
      value: "lab"
    - name: DD_CLUSTER_NAME
      value: openshift-44-lab
    - name: DD_HOSTNAME
      valueFrom:
        fieldRef:
          fieldPath: spec.nodeName
    - name: DD_KUBELET_TLS_VERIFY
      value: "false"
agents:
  enabled: true
  rbac:
    create: true
  tolerations:
    - operator: Exists
clusterAgent:
  enabled: true
  rbac:
    create: true
  env:
    - name: DD_ENV
      value: "lab"
    - name: DD_CLUSTER_NAME
      value: openshift-44-lab
    - name: DD_HOSTNAME
      valueFrom:
        fieldRef:
          fieldPath: spec.nodeName
  confd:
    etcd.yaml: |-
      cluster_check: true
      init_config:
      instances:
        - use_preview: true
          prometheus_url: https://metrics.openshift-etcd-operator/metrics
          ssl_verify: false
          bearer_token_auth: true
    kube_controller_manager.yaml: |-
      cluster_check: true
      init_config:
      instances:
        - prometheus_url: https://kube-controller-manager.openshift-kube-controller-manager/metrics
          ssl_verify: false
          bearer_token_auth: true
          leader_election: false
    kube_scheduler.yaml: |-
      cluster_check: true
      init_config:
      instances:
        - prometheus_url: https://scheduler.openshift-kube-scheduler/metrics
          ssl_verify: false
          bearer_token_auth: true
    kube_apiserver_metrics.yaml: |-
      cluster_check: true
      init_config:
      instances:
        - prometheus_url: https://apiserver.openshift-kube-apiserver/metrics
          ssl_verify: false
          bearer_token_auth: true
    coredns.yaml: |-
      cluster_check: true
      init_config:
      instances:
        - prometheus_url: http://dns-default.openshift-dns:9153/metrics
          ssl_verify: false
          bearer_token_auth: true
