datadog:
  apiKeyExistingSecret: datadog-keys
  orchestratorExplorer:
    enabled: true
  apm:
    enabled: true
  logs:
    enabled: true
    containerCollectAll: true
  processAgent:
    enabled: true
    processCollection: true
  systemProbe:
    enabled: true
  clusterChecks:
    enabled: true
  kubeStateMetricsEnabled: true
  dogstatsd:
    nonLocalTraffic: true
    useHostPort: true
  podLabelsAsTags: 
    tags.datadoghq.com/env: env
    tags.datadoghq.com/service: service
    tags.datadoghq.com/version: version
  env:
    - name: DD_ENV
      value: "lab"
    - name: DD_CLUSTER_NAME
      value: alexf-lab
    - name: DD_HOSTNAME
      valueFrom:
        fieldRef:
          fieldPath: spec.nodeName
  #     Required if kubelet readOnlyPort port is not available
  #   - name: DD_KUBELET_TLS_VERIFY
  #     value: false
  #   - name: HTTP_PROXY
  #     value: http://proxy.k8s.aws.pipsquack.ca:3128/
  #   - name: HTTPS_PROXY
  #     value: http://proxy.k8s.aws.pipsquack.ca:3128/
  confd:
    etcd.yaml: |-
      ad_identifiers:
        - etcd
      init_config:
      instances:
        - use_preview: true
          prometheus_url: https://%%host%%:2379/metrics
          ssl_ca_cert: /host/etc/kubernetes/pki/etcd/ca.crt
          ssl_cert: /host/etc/kubernetes/pki/etcd/peer.crt
          ssl_private_key: /host/etc/kubernetes/pki/etcd/peer.key
    istio.yaml: |-
      ad_identifiers:
        - proxyv2
      init_config:
      instances:
        - istio_mesh_endpoint: http://%%host%%:15090/stats/prometheus
          send_monotonic_counter: true
          send_histograms_buckets: true
agents:
  enabled: true
  rbac:
    create: true
  podAnnotations:
    sidecar.istio.io/inject: "false"
  volumeMounts:
    - mountPath: /host/etc/kubernetes/pki/etcd
      name: etcd-certs
    - mountPath: /etc/datadog-agent/conf.d/etcd.d
      name: empty-dir
    - mountPath: /etc/datadog-agent/conf.d/istio.d
      name: empty-dir
  volumes:
    - name: etcd-certs
      hostPath:
        path: /etc/kubernetes/pki/etcd
        type: DirectoryOrCreate
    - name: empty-dir
      emptyDir: {}
  tolerations:
    - operator: Exists
clusterAgent:
  enabled: true
  admissionController:
    enabled: true
    mutateUnlabelled: true
  rbac:
    create: true
  podAnnotations:
    sidecar.istio.io/inject: "false"
  env:
    - name: DD_ENV
      value: "lab"
    - name: DD_CLUSTER_NAME
      value: alexf-lab
    - name: DD_HOSTNAME
      valueFrom:
        fieldRef:
          fieldPath: spec.nodeName
  confd:
    istio.yaml: |-
      cluster_check: true
      init_config:
      instances:
        - istiod_endpoint: http://istio-pilot.istio-system:8080/metrics
