datadog:
  clusterName: alexf-aks
  apiKeyExistingSecret: datadog-keys
  collectEvents: true
  orchestratorExplorer:
    enabled: true
  securityAgent:
    compliance:
      enabled: true
      checkInterval: 5m
    runtime:
      enabled: true
      syscallMonitor:
        enabled: true
  apm:
    enabled: true
  logs:
    enabled: true
    containerCollectAll: true
  processAgent:
    processCollection: true
  systemProbe:
    enabled: true
    enableOOMKill: true
    collectDNSStats: true
  networkMonitoring:
    enabled: true
  clusterChecks:
    enabled: true
  dogstatsd:
    nonLocalTraffic: true
    useHostPort: true
  env:
    - name: DD_ENV
      value: "lab"
agents:
  tolerations:
    - operator: Exists
  containers:
    agent:
      env:
        - name: DD_KUBELET_CLIENT_CA
          value: "/host/etc/kubernetes/certs/kubeletserver.crt"
  volumeMounts:
    - mountPath: /host/etc/kubernetes/certs
      name: kubernetes-certs
  volumes:
    - name: kubernetes-certs
      hostPath:
        path: /etc/kubernetes/certs
        type: DirectoryOrCreate
clusterAgent:
  enabled: true
  admissionController:
    enabled: true
    mutateUnlabelled: true
  env:
    - name: DD_ENV
      value: "lab"
  confd:
    kube_controller_manager.yaml: |-
      cluster_check: true
      init_config:
      instances:
        - prometheus_url: https://kubernetes.default/metrics
          ssl_ca_cert: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
          bearer_token_auth: true
    kube_scheduler.yaml: |-
      cluster_check: true
      init_config:
      instances:
        - prometheus_url: https://kubernetes.default/metrics
          ssl_ca_cert: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
          bearer_token_auth: true
    kube_apiserver_metrics.yaml: |-
      cluster_check: true
      init_config:
      instances:
        - prometheus_url: https://kubernetes.default/metrics
          ssl_ca_cert: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
          bearer_token_auth: true
