datadog:
  clusterName: alexf-lab
  apiKeyExistingSecret: datadog-keys
  securityAgent:
    compliance:
      enabled: true
      checkInterval: 5m
    runtime:
      enabled: true
      syscallMonitor:
        enabled: true
  apm:
    enabled: true
  logs:
    enabled: true
    containerCollectAll: true
  processAgent:
    processCollection: true
  systemProbe:
    enableOOMKill: true
    enableTCPQueueLength: true
    collectDNSStats: true
  networkMonitoring:
    enabled: true
  dogstatsd:
    useHostPort: true
  env:
    - name: DD_ENV
      value: "lab"
  confd:
    istio.yaml: |-
      ad_identifiers:
        - proxyv2
      init_config:
      instances:
        - istio_mesh_endpoint: http://%%host%%:15090/stats/prometheus
          send_histograms_buckets: true
          send_monotonic_counter: true
agents:
  tolerations:
    - operator: Exists
  podAnnotations:
    sidecar.istio.io/inject: "false"
  volumeMounts:
    - mountPath: /etc/datadog-agent/conf.d/istio.d
      name: empty-dir
  volumes:
    - name: empty-dir
      emptyDir: {}
clusterAgent:
  admissionController:
    enabled: true
    mutateUnlabelled: true
  env:
    - name: DD_ENV
      value: "lab"
  podAnnotations:
    sidecar.istio.io/inject: "false"
  confd:
    istio.yaml: |-
      cluster_check: true
      init_config:
      instances:
        - istiod_endpoint: http://istio-pilot.istio-system:8080/metrics
